remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Pet Shark
logo: /assets/img/petsharklogoLOW.jpg
description: Project Page for Pet Shark Productions.
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
